from pydantic import BaseModel
from typing import Dict

class ExplainerRequest(BaseModel):
    # Inputs required to generate a SHAP explanation (e.g., model type, inputs, SHAP values)
    model_prediction: float
    feature_values: Dict[str, float]
    shap_values: Dict[str, float]

class ExplainerResponse(BaseModel):
    # The narrative summary generated by Gemini
    explanation: str